[project]
name = "pyo3lab-github-io"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.6.9",
    "mkdocs-static-i18n>=1.3.0",
    "mkdocs-macros-plugin>=1.2.0",
]
